"""New relations

Revision ID: d65fd24546e0
Revises: c547eb6de10b
Create Date: 2026-01-19 16:45:58.310278

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd65fd24546e0'
down_revision: Union[str, Sequence[str], None] = 'c547eb6de10b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('payments', 'task_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('payments', 'buyer_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_index(op.f('ix_payments_buyer_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_task_id'), table_name='payments')
    op.create_foreign_key(None, 'payments', 'tasks', ['task_id'], ['id'])
    op.create_foreign_key(None, 'payments', 'users', ['buyer_id'], ['id'])
    op.alter_column('projects', 'buyer_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_index(op.f('ix_projects_buyer_id'), table_name='projects')
    op.drop_index(op.f('ix_projects_description'), table_name='projects')
    op.drop_index(op.f('ix_projects_id'), table_name='projects')
    op.drop_index(op.f('ix_projects_title'), table_name='projects')
    op.create_foreign_key(None, 'projects', 'users', ['buyer_id'], ['id'])
    op.alter_column('tasks', 'project_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('tasks', 'developer_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_index(op.f('ix_tasks_developer_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_project_id'), table_name='tasks')
    op.create_foreign_key(None, 'tasks', 'projects', ['project_id'], ['id'])
    op.create_foreign_key(None, 'tasks', 'users', ['developer_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.create_index(op.f('ix_tasks_project_id'), 'tasks', ['project_id'], unique=False)
    op.create_index(op.f('ix_tasks_developer_id'), 'tasks', ['developer_id'], unique=False)
    op.alter_column('tasks', 'developer_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('tasks', 'project_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.create_index(op.f('ix_projects_title'), 'projects', ['title'], unique=False)
    op.create_index(op.f('ix_projects_id'), 'projects', ['id'], unique=False)
    op.create_index(op.f('ix_projects_description'), 'projects', ['description'], unique=False)
    op.create_index(op.f('ix_projects_buyer_id'), 'projects', ['buyer_id'], unique=False)
    op.alter_column('projects', 'buyer_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'payments', type_='foreignkey')
    op.drop_constraint(None, 'payments', type_='foreignkey')
    op.create_index(op.f('ix_payments_task_id'), 'payments', ['task_id'], unique=False)
    op.create_index(op.f('ix_payments_buyer_id'), 'payments', ['buyer_id'], unique=False)
    op.alter_column('payments', 'buyer_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('payments', 'task_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
